### ISSUE TITLE
Stopwatch.start() and Stopwatch.stop() are wrong

### ISSUE THREAD

**Issue by chinnonae** [JirayuL/stopwatch#1]
You should consider the cases where:

> 1. `start()` is called when the Stopwatch is already started.
> 2. `stop()` is called when the Stopwatch is already stopped.

PS. For `Stopwatch.getElapsed()` on this [line](https://github.com/JirayuL/stopwatch/blob/master/src/stopwatch/Stopwatch.java#L33), you should use `isRunning()` instead of doing the calculation, so it will be easier to understand.

**Comment by JirayuL** [comment]
I have change the start and stop method. For Stopwatch.getElapsed I change it to isRunning. Thank you!
